version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: /cicd/sonar/sonar-token
    DOCKER_USERNAME: /cicd/docker-credentials/username
    DOCKER_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "---- Installing Tools ----"
      - wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip -q sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
      - apt-get install -y wget apt-transport-https gnupg lsb-release
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update -y
      - apt-get install -y trivy

  pre_build:
    commands:
      - echo "---- Installing App Dependencies ----"
      - cd Swiggy_clone && npm install && cd ..

      - echo "---- SonarQube Analysis ----"
      - export PATH=$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin
      - sonar-scanner
          -Dsonar.projectKey=swiggy-clone
          -Dsonar.sources=Swiggy_clone
          -Dsonar.host.url=http://44.220.182.64:9000
          -Dsonar.login=$SONAR_TOKEN

      - echo "---- Trivy FS Scan ----"
      - trivy fs --exit-code 0 --severity HIGH,CRITICAL --format table Swiggy_clone/

      - echo "---- Docker Login ----"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL

  build:
    commands:
      - echo "---- Docker Build ----"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=$DOCKER_USERNAME/swiggy
      - cd Swiggy_clone
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

      - echo "---- Trivy Image Scan ----"
      - trivy image --exit-code 0 --severity HIGH,CRITICAL --format table $REPOSITORY_URI:$IMAGE_TAG

      - echo "---- Docker Push ----"
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - cd ..

  post_build:
    commands:
      - echo "---- Generating Artifacts ----"
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=$DOCKER_USERNAME/swiggy
      - printf '[{"name":"swiggy","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - cat imageDetail.json
      - echo "Build completed on $(date)"

artifacts:
  files:
    - imageDetail.json
    - appspec.yaml
    - taskdef.json
  discard-paths: yes
